config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'dashboard#index'

  resources :imports, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dealer.rb
class Dealer < ApplicationRecord
  validates_presence_of :name
end

app/models/import.rb
class Import
  attr_accessor :attachment

  def initialize(params)
    @attachment = params[:attachment]
  end

  def upload
    service = ImporterService.new(file: attachment, format: 'csv')
    service.import
  end
end

app/models/make.rb
class Make < ApplicationRecord
  has_many :vehicles

  validates_presence_of :name
end

app/models/model_variant.rb
class ModelVariant < ApplicationRecord
  has_many :variants
  validates_presence_of :series
end

app/models/option_type.rb
class OptionType < ApplicationRecord
  DEFAULT_TYPES = [:upholstery, :exterior_colour, :interior_colour]

  has_many :option_values

  validates_presence_of :name
end

app/models/option_value.rb
class OptionValue < ApplicationRecord
  belongs_to :option_type

  validates_presence_of :value
end

app/models/option_value_variant.rb
class OptionValueVariant < ApplicationRecord
  belongs_to :variant
  belongs_to :option_value
end

app/models/price.rb
class Price < ApplicationRecord
  MAX = (2**(0.size * 8 -2) -1)

  monetize :amount_cents

  DEFAULT_CURRENCY = 'USD'

  belongs_to :variant
  belongs_to :stock_item

  validates_presence_of :amount_cents
  validates_presence_of :amount_currency

  def display_amount
    amount.format
  end
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  monetize :amount_cents

  belongs_to :variant
  belongs_to :stock_item
  belongs_to :customer, class_name: 'User'
  belongs_to :sales_rep, class_name: 'User'

  validates_presence_of :amount_cents
  validates_presence_of :amount_currency
end

app/models/role.rb
class Role < ApplicationRecord
  module Type
    CUSTOMER    = 'Customer'.freeze
    SALES_REP   = 'SalesRep'.freeze
    TECHNICIAN  = 'Technician'.freeze
  end

  validates_presence_of :name

  class << self
    def user
      Role.find_by(name: Type::CUSTOMER)
    end

    def sales_rep
      Role.find_by(name: Type::SALES_REP)
    end

    def technician
      Role.find_by(name: Type::TECHNICIAN)
    end
  end
end

app/models/stock_item.rb
class StockItem < ApplicationRecord
  belongs_to :variant, autosave: true
  belongs_to :stock_location, autosave: true
  belongs_to :dealer, autosave: true, optional: true

  has_one :vehicle_inspection, autosave: true
  has_one :price, autosave: true
  has_one :purchase, autosave: true
end

app/models/stock_location.rb
class StockLocation < ApplicationRecord
  DEFAULT_LOCATION = 'USA'

  has_many :stock_items

  validates_presence_of :city, :province
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :role

  validates_presence_of :first_name
end

app/models/variant.rb
class Variant < ApplicationRecord
  include Filtering

  belongs_to :vehicle
  belongs_to :vehicle_specification, optional: true
  belongs_to :model_variant, optional: true

  has_many :prices
  has_many :vehicle_inspections
  has_many :option_value_variants
  has_many :option_values, through: :option_value_variants
  has_many :stock_items

  filter_by :price_min, ->(min) do
    min = min.to_i * 100 # cents
    joins(:prices).where('prices.amount_cents >= ?', min)
  end
  filter_by :price_max, ->(max) do
    max = max.to_i * 100 # cents
    joins(:prices).where('prices.amount_cents <= ?', max)
  end
  filter_by :mileage_min, ->(min) do
    joins(:vehicle_inspections).where('vehicle_inspections.mileage >= ?', min)
  end
  filter_by :mileage_max, ->(max) do
    joins(:vehicle_inspections).where('vehicle_inspections.mileage <= ?', max)
  end
  filter_by :size_id, -> (size_id) { joins(vehicle: :vehicle_type).where('vehicles.vehicle_type_id = ?', size_id) }
  filter_by :colour_id, -> (colour_id) do
    option_type = OptionType.find_by(name: :exterior_colour)
    if option_type.blank?
      none
    else
      option_values = option_type.option_values.where(id: colour_id)
      joins(:option_value_variants).where(option_value_variants: { option_value_id: colour_id })
    end
  end
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :vehicle_type, optional: true
  belongs_to :make

  has_many :variants
end

app/models/vehicle_inspection.rb
class VehicleInspection < ApplicationRecord
  MAX = (2**(0.size * 8 -2) -1)

  belongs_to :watched_by, class_name: 'User', optional: true
  belongs_to :stock_item
  belongs_to :variant
end

app/models/vehicle_specification.rb
class VehicleSpecification < ApplicationRecord
  has_many :variants
end

app/models/vehicle_type.rb
class VehicleType < ApplicationRecord
  has_many :vehicles

  validates_presence_of :name
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @pagy, @variants = pagy(filtered(Variant.all.includes(
      :vehicle_specification,
      :model_variant,
      :prices,
      option_values: [:option_type],
      vehicle: [:make, :vehicle_type]
    )))
  end

  private

    def filter_params
      params.permit(:size_id, :colour_id, :mileage_min, :mileage_max, :price_min, :price_max)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/dashboard/index.html.erb
<div class="is-radiusless">
  <section class="hero is-secondary is-dark">
    <div class="hero-body">
      <div class="container">
        <img src="https://forums.odforce.net/uploads/monthly_2017_09/V.png.369103f574897ea558177f9598bb3137.png" alt="Vehico Listo" width="75" height="75">
        <h1 class="title">Vehico Listo</h1>
      </div>
    </div>
  </section>

  <!-- FORM FOR CSV UPLOAD -->
  <section class="hero is-primary is-radiusless">
    <div class="hero-body">
      <div class="container">
        <h1 class="title">Import Vehicles</h1>
        <h2 class="subtitle">Supports CSV Only</h2>
      </div>
    </div>
  </section>

  <% if flash[:alert] %>
    <div class="notification is-danger is-full is-radiusless">
      <button class="delete"></button>
      <%= flash[:alert] %>
    </div>
  <% end %>
  <% if flash[:notice] %>
    <div class="notification is-success is-full is-radiusless">
      <button class="delete"></button>
      <%= flash[:notice] %>
    </div>
  <% end %>

  <section class="section">
    <div class="container">
      <%= form_for :import, url: imports_path, method: :post do |f| %>
        <div id="file-csv-upload-import" class="file has-name is-success">
          <label class="file-label">
            <%= f.file_field :attachment, class: 'file-input' %>
            <span class="file-cta">
              <span class="file-icon">
                <i class="fas fa-upload"></i>
              </span>
              <span class="file-label">
                Choose a file…
              </span>
            </span>
            <span class="file-name">
              No file uploaded
            </span>
          </label>
        </div>

        <br />

        <div class="control">
          <%= f.submit :Import, class: 'button is-link' %>
        </div>
      <% end %>
    </div>
  </section>

  <!-- LISTING -->
  <section class="hero is-primary">
    <div class="hero-body">
      <div class="container">
        <h1 class="title">Vehicles List</h1>
        <h2 class="subtitle">Filter</h2>
      </div>
    </div>
  </section>

  <section class="hero is-light">
    <div class="hero-body">
      <div class="container">
        <h1 class="title">Filters</h1>

        <%= form_for :variant, url: root_path, method: :get do |f| %>

          <div class="select is-dark">
            <%= select_tag :size_id, options_from_collection_for_select(VehicleType.all.collect, :id, :name, params[:size_id]), include_blank: false, prompt: 'Size' %>
          </div>

          <div class="select is-dark">
            <%= select_tag :colour_id, options_from_collection_for_select(OptionType.find_by(name: :exterior_colour).option_values, :id, :value, params[:colour_id]), include_blank: false, prompt: 'Exterior Colour' %>
          </div>

          <div class="field" style="display: inline;">
            <div class="control" style="display: inline;">
              <%= text_field_tag :mileage_min, '', class: "input is-dark column is-2", placeholder: "Mileage Min", style: "display: inline;", value: params[:mileage_min] %>
              <%= text_field_tag :mileage_max, '', class: "input is-dark column is-2", placeholder: "Mileage Max", style: "display: inline;", value: params[:mileage_max] %>
              </span><%= text_field_tag :price_min, '', class: "input is-dark column is-1", placeholder: "Price Min", style: "display: inline;", value: params[:price_min] %>
              <%= text_field_tag :price_max, '', class: "input is-dark column is-1", placeholder: "Price Max", style: "display: inline;", value: params[:price_max] %>
            </div>
          </div>

          <div class="control" style="display: inline;">
            <%= f.submit :Filter, class: 'button is-link' %>
          </div>

        <% end %>

      </div>
    </div>
  </section>


  <section class="section">
    <div class="container">
      <div class="columns is-multiline">
        <% @variants.each.with_index do |variant, index| %>
          <%= render 'vehicles/variant', variant: variant %>
          <% if (index % 2 == 1) && index > 0 %>
            <div class="column is-12"><hr /></div>
          <% end %>
        <% end %>

    </div>
      <%== pagy_nav(@pagy) %>
    </div>
  </section>

</div>


<!-- CUSTOM JAVASCRIPTS -->
<script>
  const fileInput = document.querySelector('#file-csv-upload-import input[type=file]');
  fileInput.onchange = () => {
    if (fileInput.files.length > 0) {
      const fileName = document.querySelector('#file-csv-upload-import .file-name');
      fileName.textContent = fileInput.files[0].name;
    }
  }

  document.addEventListener('DOMContentLoaded', () => {
    (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
      $notification = $delete.parentNode;

      $delete.addEventListener('click', () => {
        $notification.parentNode.removeChild($notification);
      });
    });
  });
</script>